version: '3'

services:
  web:
    build: ./web
    container_name: web-container
    expose:
      - "3000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    depends_on:
      - web
    command: tunnel --url http://web:3000
