version: '3'

services:
  web:
    build: ./web
    container_name: web-container
    expose:
      - "3000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-container
    depends_on:
      - web
    volumes:
      - ./ngrok/ngrok.yml:/ngrok.yml
    command: start --config /ngrok.yml --all
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
