services:
  web:
    restart: "no"
    healthcheck:
      disable: false
    environment:
      - NODE_ENV=development
      - USE_HTTPS=false

  cloudflared:
    image: busybox
    restart: "no"
    depends_on: []
    profiles: []
    entrypoint: ["sh", "-c", "echo 'Skipping tunnel in dev mode, busybox is holding down the fort :)'"]
    command: []